/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seetatech_sdk_rtsp_RtspClient */

#ifndef _Included_com_seetatech_sdk_rtsp_RtspClient
#define _Included_com_seetatech_sdk_rtsp_RtspClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seetatech_sdk_rtsp_RtspClient
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_seetatech_sdk_rtsp_RtspClient_create
  (JNIEnv *, jobject);

/*
 * Class:     com_seetatech_sdk_rtsp_RtspClient
 * Method:    nStart
 * Signature: (JLjava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_seetatech_sdk_rtsp_RtspClient_nStart
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     com_seetatech_sdk_rtsp_RtspClient
 * Method:    nRetry
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_seetatech_sdk_rtsp_RtspClient_nRetry
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_seetatech_sdk_rtsp_RtspClient
 * Method:    nStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_seetatech_sdk_rtsp_RtspClient_nStop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_seetatech_sdk_rtsp_RtspClient
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_seetatech_sdk_rtsp_RtspClient_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
